{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16ee98a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "from IPython.display import display, HTML\n",
    "\n",
    "display(HTML(\"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"pt-BR\">\n",
    "<head>\n",
    "<meta charset=\"utf-8\" />\n",
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n",
    "<title>Coração com partículas azuis + Compartilhar no WhatsApp</title>\n",
    "<style>\n",
    "  :root{\n",
    "    --bg: #071022;\n",
    "    --card: rgba(255,255,255,0.03);\n",
    "    --accent: #3aa0ff;\n",
    "    --text: #e6eef8;\n",
    "    --whats: #25D366;\n",
    "  }\n",
    "  html,body{height:100%;margin:0;font-family:Inter,system-ui,Arial;background:linear-gradient(180deg,#071022,#041227 80%);color:var(--text)}\n",
    "  .wrap{\n",
    "    min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px;\n",
    "  }\n",
    "  .card{\n",
    "    width:720px;max-width:96vw;background:linear-gradient(180deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01));\n",
    "    border-radius:16px;padding:18px;box-shadow:0 10px 30px rgba(2,6,23,0.6);\n",
    "    display:grid;grid-template-columns:420px 1fr;gap:18px;align-items:center;\n",
    "  }\n",
    "  .canvas-wrap{position:relative;height:420px;border-radius:12px;overflow:hidden;background:radial-gradient(circle at 30% 20%, rgba(58,160,255,0.06), transparent 20%), #021226;}\n",
    "  canvas{display:block;width:100%;height:100%;}\n",
    "  .info{padding:6px 8px;}\n",
    "  h1{font-size:18px;margin:6px 0}\n",
    "  p{color:#a9c6e6;font-size:13px;margin:6px 0 14px}\n",
    "  .controls{display:flex;flex-direction:column;gap:10px}\n",
    "  .url-box{background:transparent;border:1px solid rgba(255,255,255,0.04);padding:10px;border-radius:8px;color:var(--text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n",
    "  .row{display:flex;gap:8px;flex-wrap:wrap}\n",
    "  button, .link{\n",
    "    padding:10px 12px;border-radius:10px;border:0;cursor:pointer;font-weight:600;\n",
    "  }\n",
    "  .btn-copy{background:transparent;border:1px solid rgba(255,255,255,0.06);color:var(--text)}\n",
    "  .btn-whats{background:var(--whats);color:white;box-shadow:0 8px 20px rgba(37,211,102,0.15)}\n",
    "  .btn-custom{background:linear-gradient(90deg,#4fb3ff,#3aa0ff);color:white}\n",
    "  .hint{font-size:12px;color:#8faed8;margin-top:6px}\n",
    "  .small{font-size:12px;color:#93b8df}\n",
    "  @media (max-width:820px){\n",
    "    .card{grid-template-columns:1fr;gap:12px}\n",
    "    .canvas-wrap{height:320px}\n",
    "  }\n",
    "</style>\n",
    "</head>\n",
    "<body>\n",
    "  <div class=\"wrap\">\n",
    "    <div class=\"card\" role=\"main\" aria-labelledby=\"title\">\n",
    "      <div class=\"canvas-wrap\" id=\"canvasWrap\" title=\"Clique no coração para uma explosão de partículas\">\n",
    "        <canvas id=\"c\"></canvas>\n",
    "      </div>\n",
    "\n",
    "      <div class=\"info\">\n",
    "        <h1 id=\"title\">Coração com partículas azuis 💙</h1>\n",
    "        <p>Clique no coração para uma explosão de partículas azuis. Use os botões para copiar ou compartilhar no WhatsApp.</p>\n",
    "\n",
    "        <div class=\"controls\">\n",
    "          <div class=\"url-box\" id=\"shareUrl\" contenteditable=\"false\" aria-label=\"URL para compartilhar\">https://exemplo.com/coracao</div>\n",
    "\n",
    "          <div class=\"row\">\n",
    "            <button class=\"btn-copy\" id=\"copyBtn\" aria-label=\"Copiar link\">Copiar link</button>\n",
    "            <button class=\"btn-whats\" id=\"whatsBtn\" aria-label=\"Compartilhar no WhatsApp\">Compartilhar no WhatsApp</button>\n",
    "            <button class=\"btn-custom\" id=\"usePageBtn\" title=\"Definir link como a URL atual\">Usar URL desta página</button>\n",
    "          </div>\n",
    "\n",
    "          <div class=\"hint\">Dica: para testar no celular, abra este arquivo via Live Server e clique no botão do WhatsApp — ele abrirá o app (ou WhatsApp Web no desktop).</div>\n",
    "          <div class=\"small\" id=\"status\" aria-live=\"polite\"></div>\n",
    "        </div>\n",
    "      </div>\n",
    "    </div>\n",
    "  </div>\n",
    "\n",
    "<script>\n",
    "/*\n",
    "  coracao-particulas-whatsapp.html\n",
    "  - Coração desenhado com path no canvas\n",
    "  - Partículas azuis nascem continuamente e explodem ao clicar no coração\n",
    "  - Botões: copiar link, compartilhar no WhatsApp (usa shareUrl ou location.href), definir URL para location.href\n",
    "*/\n",
    "\n",
    "// Canvas e dimensionamento\n",
    "const canvas = document.getElementById('c');\n",
    "const wrap = document.getElementById('canvasWrap');\n",
    "const ctx = canvas.getContext('2d');\n",
    "\n",
    "function resize() {\n",
    "  const dpr = window.devicePixelRatio || 1;\n",
    "  canvas.width = wrap.clientWidth * dpr;\n",
    "  canvas.height = wrap.clientHeight * dpr;\n",
    "  canvas.style.width = wrap.clientWidth + 'px';\n",
    "  canvas.style.height = wrap.clientHeight + 'px';\n",
    "  ctx.setTransform(dpr,0,0,dpr,0,0);\n",
    "}\n",
    "window.addEventListener('resize', resize);\n",
    "resize();\n",
    "\n",
    "// Heart path (relative coordinates) - we'll scale/translate to fit box\n",
    "function createHeartPath(x, y, size) {\n",
    "  const path = new Path2D();\n",
    "  // Using a common heart bezier shape\n",
    "  const topX = x, topY = y - size*0.2;\n",
    "  path.moveTo(topX, topY + size*0.3);\n",
    "  path.bezierCurveTo(topX - size*0.6, topY - size*0.55, topX - size*1.15, topY + size*0.4, topX, topY + size);\n",
    "  path.bezierCurveTo(topX + size*1.15, topY + size*0.4, topX + size*0.6, topY - size*0.55, topX, topY + size*0.3);\n",
    "  return path;\n",
    "}\n",
    "\n",
    "// Particle system\n",
    "const particles = [];\n",
    "const maxParticles = 700;\n",
    "function rand(min,max){ return Math.random()*(max-min)+min; }\n",
    "\n",
    "function emit(x,y,spread=1,count=10,power=2){\n",
    "  for(let i=0;i<count;i++){\n",
    "    if(particles.length > maxParticles) particles.shift();\n",
    "    const ang = Math.random()*Math.PI*2;\n",
    "    const speed = rand(0.2, power) * spread;\n",
    "    const size = rand(1,4);\n",
    "    const life = rand(700,1800);\n",
    "    const hue = rand(200,220); // azul\n",
    "    const sat = rand(60,90);\n",
    "    particles.push({\n",
    "      x, y,\n",
    "      vx: Math.cos(ang)*speed + rand(-0.6,0.6),\n",
    "      vy: Math.sin(ang)*speed + rand(-0.6,0.6) - 0.3,\n",
    "      size,\n",
    "      life,\n",
    "      born: performance.now(),\n",
    "      hue, sat\n",
    "    });\n",
    "  }\n",
    "}\n",
    "\n",
    "// Continuous gentle emission from heart interior\n",
    "let heartCenter = {x: 0, y:0, size: 1};\n",
    "function continuousEmit(){\n",
    "  // emit few particles from random points near center\n",
    "  for(let i=0;i<2;i++){\n",
    "    const ox = heartCenter.x + rand(-heartCenter.size*0.25, heartCenter.size*0.25);\n",
    "    const oy = heartCenter.y + rand(-heartCenter.size*0.15, heartCenter.size*0.15);\n",
    "    emit(ox,oy,0.9,1,0.9);\n",
    "  }\n",
    "}\n",
    "\n",
    "// animation loop\n",
    "let last = performance.now();\n",
    "function tick(now){\n",
    "  const dt = now - last;\n",
    "  last = now;\n",
    "  // clear\n",
    "  ctx.clearRect(0,0,canvas.width,canvas.height);\n",
    "\n",
    "  // determine heart placement (center-left of canvas)\n",
    "  const W = wrap.clientWidth;\n",
    "  const H = wrap.clientHeight;\n",
    "  const cx = W/2;\n",
    "  const cy = H/2 - 10;\n",
    "  const baseSize = Math.min(W, H) * 0.22; // heart size\n",
    "  heartCenter = {x: cx, y: cy - baseSize*0.05, size: baseSize};\n",
    "\n",
    "  // draw soft glowing background heart (filled)\n",
    "  const heartPath = createHeartPath(cx, cy - baseSize*0.15, baseSize);\n",
    "  // subtle glow\n",
    "  ctx.save();\n",
    "  ctx.shadowColor = 'rgba(60,150,255,0.12)';\n",
    "  ctx.shadowBlur = 40;\n",
    "  ctx.fillStyle = 'rgba(36,98,210,0.06)';\n",
    "  ctx.fill(heartPath);\n",
    "  ctx.restore();\n",
    "\n",
    "  // draw main heart with small gradient\n",
    "  const g = ctx.createLinearGradient(cx - baseSize, cy - baseSize, cx + baseSize, cy + baseSize);\n",
    "  g.addColorStop(0, '#1e6fe8');\n",
    "  g.addColorStop(1, '#2fb0ff');\n",
    "  ctx.fillStyle = g;\n",
    "  ctx.fill(heartPath);\n",
    "\n",
    "  // small inner shine\n",
    "  ctx.save();\n",
    "  ctx.globalCompositeOperation = 'screen';\n",
    "  ctx.fillStyle = 'rgba(255,255,255,0.07)';\n",
    "  ctx.translate(cx - baseSize*0.15, cy - baseSize*0.35);\n",
    "  ctx.scale(1,0.8);\n",
    "  ctx.fill(createHeartPath(0,0, baseSize*0.6));\n",
    "  ctx.restore();\n",
    "\n",
    "  // spawn gentle particles\n",
    "  continuousEmit();\n",
    "\n",
    "  // update particles\n",
    "  const nowMs = performance.now();\n",
    "  for(let i = particles.length-1; i>=0; i--){\n",
    "    const p = particles[i];\n",
    "    const age = nowMs - p.born;\n",
    "    const t = age / p.life;\n",
    "    if(t >= 1){ particles.splice(i,1); continue; }\n",
    "    // physics\n",
    "    p.vy += 0.0015 * dt; // gravity small\n",
    "    p.vx *= 0.999;\n",
    "    p.vy *= 0.999;\n",
    "    p.x += p.vx * dt * 0.06;\n",
    "    p.y += p.vy * dt * 0.06;\n",
    "\n",
    "    // draw\n",
    "    const alpha = Math.max(0, 1 - t);\n",
    "    ctx.beginPath();\n",
    "    ctx.globalAlpha = alpha;\n",
    "    // blue tone with small hue variation\n",
    "    ctx.fillStyle = `hsla(${p.hue}, ${p.sat}%, 55%, ${alpha})`;\n",
    "    ctx.arc(p.x, p.y, p.size, 0, Math.PI*2);\n",
    "    ctx.fill();\n",
    "    ctx.globalAlpha = 1;\n",
    "  }\n",
    "\n",
    "  requestAnimationFrame(tick);\n",
    "}\n",
    "requestAnimationFrame(tick);\n",
    "\n",
    "// Interaction: click on canvas, check if inside heart, then explode\n",
    "canvas.addEventListener('click', (ev) => {\n",
    "  const rect = canvas.getBoundingClientRect();\n",
    "  const x = (ev.clientX - rect.left);\n",
    "  const y = (ev.clientY - rect.top);\n",
    "  // recreate heart path with current placement to test\n",
    "  const cx = wrap.clientWidth/2;\n",
    "  const cy = wrap.clientHeight/2 - 10;\n",
    "  const baseSize = Math.min(wrap.clientWidth, wrap.clientHeight) * 0.22;\n",
    "  const path = createHeartPath(cx, cy - baseSize*0.15, baseSize);\n",
    "  // use isPointInPath\n",
    "  if(ctx.isPointInPath(path, x, y)){\n",
    "    // explosion\n",
    "    emit(x, y, 2.5, 120, 3.2);\n",
    "    // small pulse animation on heart (scale)\n",
    "    pulseHeart();\n",
    "    setStatus('Explosão de partículas! ✨', 1400);\n",
    "  } else {\n",
    "    // small ripple for clicks outside\n",
    "    emit(x, y, 1, 12, 1.8);\n",
    "  }\n",
    "});\n",
    "\n",
    "// heart pulse (visual transform by temporarily drawing overlay)\n",
    "let pulsing = false;\n",
    "function pulseHeart(){\n",
    "  if(pulsing) return;\n",
    "  pulsing = true;\n",
    "  const original = ctx.globalCompositeOperation;\n",
    "  let start = performance.now();\n",
    "  const duration = 280;\n",
    "  (function frame(now){\n",
    "    const t = (now - start) / duration;\n",
    "    if(t >= 1){ pulsing = false; ctx.globalCompositeOperation = original; return; }\n",
    "    requestAnimationFrame(frame);\n",
    "  })(start);\n",
    "}\n",
    "\n",
    "// UI: share/copy buttons\n",
    "const urlBox = document.getElementById('shareUrl');\n",
    "const copyBtn = document.getElementById('copyBtn');\n",
    "const whatsBtn = document.getElementById('whatsBtn');\n",
    "const usePageBtn = document.getElementById('usePageBtn');\n",
    "const statusEl = document.getElementById('status');\n",
    "\n",
    "function setStatus(msg, ms=1500){\n",
    "  statusEl.textContent = msg || '';\n",
    "  if(ms) setTimeout(()=> statusEl.textContent = '', ms);\n",
    "}\n",
    "\n",
    "copyBtn.addEventListener('click', async () => {\n",
    "  const url = urlBox.textContent.trim();\n",
    "  try{\n",
    "    await navigator.clipboard.writeText(url);\n",
    "    setStatus('Link copiado para a área de transferência!');\n",
    "  }catch(e){\n",
    "    const ta = document.createElement('textarea');\n",
    "    ta.value = url;\n",
    "    document.body.appendChild(ta);\n",
    "    ta.select();\n",
    "    try { document.execCommand('copy'); setStatus('Link copiado (fallback).'); }\n",
    "    catch(err){ setStatus('Não foi possível copiar automaticamente.'); }\n",
    "    document.body.removeChild(ta);\n",
    "  }\n",
    "});\n",
    "\n",
    "usePageBtn.addEventListener('click', () => {\n",
    "  const pageUrl = location.href;\n",
    "  urlBox.textContent = pageUrl;\n",
    "  setStatus('URL definida para a página atual.');\n",
    "});\n",
    "\n",
    "// WhatsApp sharing\n",
    "whatsBtn.addEventListener('click', () => {\n",
    "  const targetUrl = urlBox.textContent.trim() || location.href;\n",
    "  const text = encodeURIComponent(`Olha esse coração 💙\\n${targetUrl}`);\n",
    "  // universal wa.me link\n",
    "  const wa = `https://wa.me/?text=${text}`;\n",
    "  // open in new tab/window (on mobile will open app)\n",
    "  window.open(wa, '_blank', 'noopener');\n",
    "  setStatus('Abrindo WhatsApp...');\n",
    "});\n",
    "\n",
    "// Optionally: allow pressing Enter on urlBox to update (if made editable). For safety it's not editable by default.\n",
    "// You can change the URL by editing the content of urlBox in code or toggling contenteditable if desired.\n",
    "\n",
    "</script>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20023bfc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
